### ISSUE TITLE
tikv should provide error message if it can't start

### ISSUE THREAD

**Issue by morgo** [tikv/tikv#3387]
## Bug Report

**What version of Rust are you using?**
I'm using a binary provided by PingCAP:
```
[ec2-user@ip-10-0-3-16 tidb-latest-linux-amd64]$ bin/tikv-server --version
TiKV
Release Version:   2.1.0-beta
Git Commit Hash:   ecde5e3066538e86c1bab82b85768c309fc764a5
Git Commit Branch: master
UTC Build Time:    2018-08-01 10:29:26
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
```
**What operating system and CPU are you using?**
```
[ec2-user@ip-10-0-3-16 tidb-latest-linux-amd64]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x3c
cpu MHz         : 2399.943
cache size      : 30720 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4800.14
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
**What did you do?**
`./bin/tikv-server --pd="127.0.0.1:2379" --data-dir=tikv --log-level=debug`
**What did you expect to see?**
An error message saying that tikv could not be started because kernel settings were not as expected.
**What did you see instead?**
tikv-server exits without an error message (even if I changed the log-level to trace, or tried a log-file instead).  After I ran the following (copied from ansible playbook), it worked as expected:

```
cat << EOF > /tmp/tidb.conf
ec2-user        soft        nofile        1000000
ec2-user        hard        nofile        1000000
ec2-user        soft        core          unlimited
ec2-user        soft        stack         10240
EOF

sudo cp /tmp/tidb.conf /etc/security/limits.d/
sudo sysctl -w net.core.somaxconn=32768
sudo sysctl -w vm.swappiness=0
sudo sysctl -w net.ipv4.tcp_syncookies=0
sudo sysctl -w fs.file-max=1000000
```
I realize binary install like this is not recommended.  There may be cases with other install types where kernel params change, and tikv fails to start.  It would be nice to be able to provide a reason for the exit.

**Comment by breeswish** [comment]
Thanks for your report. Do you mean that after executing command `./bin/tikv-server --pd="127.0.0.1:2379" --data-dir=tikv --log-level=debug` you got nothing in output and it just stopped?

**Comment by morgo** [comment]
@breeswish that is correct.

**Comment by breeswish** [comment]
@morgo Thanks! You are correct, we expect it to print error messages in this scenario.

**Comment by brson** [comment]
When I run locally without the max file descriptors set I see:

```
[ERROR] [tikv-server.rs:90] ["Limit(\"the maximum number of open file descriptors is too small, got 65536, expect greater or equal to 82920\")"]
```

Is this fixed?

**Comment by breeswish** [comment]
@brson Maybe not. We need investigation. It is very likely that currently checked fd number is not enough.

**Comment by Hoverbear** [comment]
@morgo I suspect we are logging it but the logger is being dropped before it can print. The master or 3.0.0 release should be fixed. (I checked just 2 weeks ago).

I'll close this since it's fixed on master.

**Comment by morgo** [comment]
I can still reproduce this against daily builds.  First invokation showed me some info, subsequent not event that:
```
[ec2-user@ip-172-31-31-227 tidb-latest-linux-amd64]$ ./bin/tikv-server --pd=":2379" --data-dir=tikv
[2019/03/26 22:09:46.811 +00:00] [INFO] [mod.rs:25] ["Welcome to TiKV."]
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] []
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] ["Release Version:   3.0.0-beta.1"]
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] ["Git Commit Hash:   c92984bd780d4d7b4b42f7fae81f02a3a045b285"]
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] ["Git Commit Branch: master"]
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] ["UTC Build Time:    2019-03-26 03:31:14"]
[2019/03/26 22:09:46.814 +00:00] [INFO] [mod.rs:27] ["Rust Version:      rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)"]
[2019/03/26 22:09:46.815 +00:00] [INFO] [mod.rs:29] []
[2019/03/26 22:09:46.815 +00:00] [INFO] [config.rs:164] ["no advertise-addr is specified, falling back to default addr"] [addr=127.0.0.1:20160]
[2019/03/26 22:09:46.816 +00:00] [INFO] [tikv-server.rs:494] ["using config"] [config="{\"log-level\":\"info\",\"log-file\":\"\",\"log-rotation-timespan\":\"1d\",\"panic-when-unexpected-key-or-data\":false,\"readpool\":{\"storage\":{\"high-concurrency\":4,\"normal-concurrency\":4,\"low-concurrency\":4,\"max-tasks-per-worker-high\":2000,\"max-tasks-per-worker-normal\":2000,\"max-tasks-per-worker-low\":2000,\"stack-size\":\"10MB\"},\"coprocessor\":{\"high-concurrency\":8,\"normal-concurrency\":8,\"low-concurrency\":8,\"max-tasks-per-worker-high\":2000,\"max-tasks-per-worker-normal\":2000,\"max-tasks-per-worker-low\":2000,\"stack-size\":\"10MB\"}},\"server\":{\"addr\":\"127.0.0.1:20160\",\"advertise-addr\":\"127.0.0.1:20160\",\"status-addr\":\"127.0.0.1:20180\",\"status-thread-pool-size\":1,\"grpc-compression-type\":\"none\",\"grpc-concurrency\":4,\"grpc-concurrent-stream\":1024,\"grpc-raft-conn-num\":1,\"grpc-stream-initial-window-size\":\"2MB\",\"grpc-keepalive-time\":\"10s\",\"grpc-keepalive-timeout\":\"3s\",\"concurrent-send-snap-limit\":32,\"concurrent-recv-snap-limit\":32,\"end-point-recursion-limit\":1000,\"end-point-stream-channel-size\":8,\"end-point-batch-row-limit\":64,\"end-point-stream-batch-row-limit\":128,\"end-point-request-max-handle-duration\":\"1m\",\"snap-max-write-bytes-per-sec\":\"100MB\",\"snap-max-total-size\":\"0KB\",\"stats-concurrency\":1,\"heavy-load-threshold\":300,\"heavy-load-wait-duration\":\"1ms\",\"labels\":{}},\"storage\":{\"data-dir\":\"/home/ec2-user/tidb-latest-linux-amd64/tikv\",\"gc-ratio-threshold\":1.1,\"max-key-size\":4096,\"scheduler-notify-capacity\":10240,\"scheduler-concurrency\":2048000,\"scheduler-worker-pool-size\":4,\"scheduler-pending-write-threshold\":\"100MB\"},\"pd\":{\"endpoints\":[\":2379\"]},\"metric\":{\"interval\":\"15s\",\"address\":\"\",\"job\":\"tikv\"},\"raftstore\":{\"sync-log\":true,\"prevote\":true,\"raftdb-path\":\"/home/ec2-user/tidb-latest-linux-amd64/tikv/raft\",\"capacity\":\"0KB\",\"raft-base-tick-interval\":\"1s\",\"raft-heartbeat-ticks\":2,\"raft-election-timeout-ticks\":10,\"raft-min-election-timeout-ticks\":10,\"raft-max-election-timeout-ticks\":20,\"raft-max-size-per-msg\":\"1MB\",\"raft-max-inflight-msgs\":256,\"raft-entry-max-size\":\"8MB\",\"raft-log-gc-tick-interval\":\"10s\",\"raft-log-gc-threshold\":50,\"raft-log-gc-count-limit\":73728,\"raft-log-gc-size-limit\":\"72MB\",\"raft-entry-cache-life-time\":\"30s\",\"raft-reject-transfer-leader-duration\":\"3s\",\"split-region-check-tick-interval\":\"10s\",\"region-split-check-diff\":\"6MB\",\"region-compact-check-interval\":\"5m\",\"clean-stale-peer-delay\":\"11m\",\"region-compact-check-step\":100,\"region-compact-min-tombstones\":10000,\"region-compact-tombstones-percent\":30,\"pd-heartbeat-tick-interval\":\"1m\",\"pd-store-heartbeat-tick-interval\":\"10s\",\"snap-mgr-gc-tick-interval\":\"1m\",\"snap-gc-timeout\":\"4h\",\"lock-cf-compact-interval\":\"10m\",\"lock-cf-compact-bytes-threshold\":\"256MB\",\"notify-capacity\":40960,\"messages-per-tick\":4096,\"max-peer-down-duration\":\"5m\",\"max-leader-missing-duration\":\"2h\",\"abnormal-leader-missing-duration\":\"10m\",\"peer-stale-state-check-interval\":\"5m\",\"leader-transfer-max-log-lag\":10,\"snap-apply-batch-size\":\"10MB\",\"consistency-check-interval\":\"0s\",\"report-region-flow-interval\":\"1m\",\"raft-store-max-leader-lease\":\"9s\",\"right-derive-when-split\":true,\"allow-remove-leader\":false,\"merge-max-log-gap\":10,\"merge-check-tick-interval\":\"10s\",\"use-delete-range\":false,\"cleanup-import-sst-interval\":\"10m\",\"local-read-batch-size\":1024,\"apply-max-batch-size\":1024,\"apply-pool-size\":2,\"store-max-batch-size\":1024,\"store-pool-size\":2,\"future-poll-size\":1},\"coprocessor\":{\"split-region-on-table\":true,\"batch-split-limit\":10,\"region-max-size\":\"144MB\",\"region-split-size\":\"96MB\",\"region-max-keys\":1440000,\"region-split-keys\":960000},\"rocksdb\":{\"wal-recovery-mode\":2,\"wal-dir\":\"\",\"wal-ttl-seconds\":0,\"wal-size-limit\":\"0KB\",\"max-total-wal-size\":\"4GB\",\"max-background-jobs\":6,\"max-manifest-file-size\":\"128MB\",\"create-if-missing\":true,\"max-open-files\":40960,\"enable-statistics\":true,\"stats-dump-period\":\"10m\",\"compaction-readahead-size\":\"0KB\",\"info-log-max-size\":\"1GB\",\"info-log-roll-time\":\"0s\",\"info-log-keep-log-file-num\":10,\"info-log-dir\":\"\",\"rate-bytes-per-sec\":\"0KB\",\"rate-limiter-mode\":2,\"auto-tuned\":false,\"bytes-per-sync\":\"1MB\",\"wal-bytes-per-sync\":\"512KB\",\"max-sub-compactions\":1,\"writable-file-max-buffer-size\":\"1MB\",\"use-direct-io-for-flush-and-compaction\":false,\"enable-pipelined-write\":true,\"defaultcf\":{\"block-size\":\"64KB\",\"block-cache-size\":\"245MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":true,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"lz4\",\"lz4\",\"lz4\",\"zstd\",\"zstd\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"512MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":4,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":3,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":1024,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"writecf\":{\"block-size\":\"64KB\",\"block-cache-size\":\"147MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":false,\"whole-key-filtering\":false,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"lz4\",\"lz4\",\"lz4\",\"zstd\",\"zstd\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"512MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":4,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":3,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":4294967296,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"lockcf\":{\"block-size\":\"16KB\",\"block-cache-size\":\"256MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":false,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"no\",\"no\",\"no\",\"no\",\"no\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"128MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":1,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":0,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit[ec2-user@ip-172-31-31-227 tidb-latest-linux-amd64]$
[ec2-user@ip-172-31-31-227 tidb-latest-linux-amd64]$ ./bin/tikv-server --pd="localhost:2379" --data-dir=tikv --log-level=debug
[ec2-user@ip-172-31-31-227 tidb-latest-linux-amd64]$ ./bin/tikv-server --pd=":2379" --data-dir=tikv && echo works || echo failed
failed
```

**Comment by morgo** [comment]
If you are having trouble reproducing, I recommend trying this:
```
ulimit -n 1024 # default on my system, many others
/bin/tikv-server --pd=":2379" --data-dir=tikv
/bin/tikv-server --pd=":2379" --data-dir=tikv
```
The first time it prints that nice config dump and exits without error, the second time it just gives no feedback.  If I change the global limit to `1000000` everything works, I change it back to `1024`, same problem.

**Comment by brson** [comment]
I think this is a dupe of https://github.com/tikv/tikv/issues/4328 and https://github.com/tikv/tikv/issues/4358

**Comment by morgo** [comment]
Confirming that this is now fixed!  I reliably get an error now:
```
[ec2-user@ip-10-0-0-249 tidb-latest-linux-amd64]$ ./bin/tikv-server --pd=":2379" --data-dir=tikv
[2019/03/31 16:19:26.016 +00:00] [INFO] [mod.rs:25] ["Welcome to TiKV."]
[2019/03/31 16:19:26.017 +00:00] [INFO] [mod.rs:27] []
[2019/03/31 16:19:26.018 +00:00] [INFO] [mod.rs:27] ["Release Version:   3.0.0-beta.1"]
[2019/03/31 16:19:26.019 +00:00] [INFO] [mod.rs:27] ["Git Commit Hash:   8565f99812d7375f4f0b18c304b6df13bb5c4865"]
[2019/03/31 16:19:26.020 +00:00] [INFO] [mod.rs:27] ["Git Commit Branch: master"]
[2019/03/31 16:19:26.020 +00:00] [INFO] [mod.rs:27] ["UTC Build Time:    2019-03-30 12:34:58"]
[2019/03/31 16:19:26.024 +00:00] [INFO] [mod.rs:27] ["Rust Version:      rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)"]
[2019/03/31 16:19:26.025 +00:00] [INFO] [mod.rs:29] []
[2019/03/31 16:19:26.026 +00:00] [INFO] [config.rs:164] ["no advertise-addr is specified, falling back to default addr"] [addr=127.0.0.1:20160]
[2019/03/31 16:19:26.026 +00:00] [INFO] [tikv-server.rs:494] ["using config"] [config="{\"log-level\":\"info\",\"log-file\":\"\",\"log-rotation-timespan\":\"1d\",\"panic-when-unexpected-key-or-data\":false,\"readpool\":{\"storage\":{\"high-concurrency\":4,\"normal-concurrency\":4,\"low-concurrency\":4,\"max-tasks-per-worker-high\":2000,\"max-tasks-per-worker-normal\":2000,\"max-tasks-per-worker-low\":2000,\"stack-size\":\"10MB\"},\"coprocessor\":{\"high-concurrency\":8,\"normal-concurrency\":8,\"low-concurrency\":8,\"max-tasks-per-worker-high\":2000,\"max-tasks-per-worker-normal\":2000,\"max-tasks-per-worker-low\":2000,\"stack-size\":\"10MB\"}},\"server\":{\"addr\":\"127.0.0.1:20160\",\"advertise-addr\":\"127.0.0.1:20160\",\"status-addr\":\"127.0.0.1:20180\",\"status-thread-pool-size\":1,\"grpc-compression-type\":\"none\",\"grpc-concurrency\":4,\"grpc-concurrent-stream\":1024,\"grpc-raft-conn-num\":1,\"grpc-stream-initial-window-size\":\"2MB\",\"grpc-keepalive-time\":\"10s\",\"grpc-keepalive-timeout\":\"3s\",\"concurrent-send-snap-limit\":32,\"concurrent-recv-snap-limit\":32,\"end-point-recursion-limit\":1000,\"end-point-stream-channel-size\":8,\"end-point-batch-row-limit\":64,\"end-point-stream-batch-row-limit\":128,\"end-point-request-max-handle-duration\":\"1m\",\"snap-max-write-bytes-per-sec\":\"100MB\",\"snap-max-total-size\":\"0KB\",\"stats-concurrency\":1,\"heavy-load-threshold\":300,\"heavy-load-wait-duration\":\"1ms\",\"labels\":{}},\"storage\":{\"data-dir\":\"/home/ec2-user/tidb-latest-linux-amd64/tikv\",\"gc-ratio-threshold\":1.1,\"max-key-size\":4096,\"scheduler-notify-capacity\":10240,\"scheduler-concurrency\":2048000,\"scheduler-worker-pool-size\":4,\"scheduler-pending-write-threshold\":\"100MB\"},\"pd\":{\"endpoints\":[\":2379\"]},\"metric\":{\"interval\":\"15s\",\"address\":\"\",\"job\":\"tikv\"},\"raftstore\":{\"sync-log\":true,\"prevote\":true,\"raftdb-path\":\"/home/ec2-user/tidb-latest-linux-amd64/tikv/raft\",\"capacity\":\"0KB\",\"raft-base-tick-interval\":\"1s\",\"raft-heartbeat-ticks\":2,\"raft-election-timeout-ticks\":10,\"raft-min-election-timeout-ticks\":10,\"raft-max-election-timeout-ticks\":20,\"raft-max-size-per-msg\":\"1MB\",\"raft-max-inflight-msgs\":256,\"raft-entry-max-size\":\"8MB\",\"raft-log-gc-tick-interval\":\"10s\",\"raft-log-gc-threshold\":50,\"raft-log-gc-count-limit\":73728,\"raft-log-gc-size-limit\":\"72MB\",\"raft-entry-cache-life-time\":\"30s\",\"raft-reject-transfer-leader-duration\":\"3s\",\"split-region-check-tick-interval\":\"10s\",\"region-split-check-diff\":\"6MB\",\"region-compact-check-interval\":\"5m\",\"clean-stale-peer-delay\":\"11m\",\"region-compact-check-step\":100,\"region-compact-min-tombstones\":10000,\"region-compact-tombstones-percent\":30,\"pd-heartbeat-tick-interval\":\"1m\",\"pd-store-heartbeat-tick-interval\":\"10s\",\"snap-mgr-gc-tick-interval\":\"1m\",\"snap-gc-timeout\":\"4h\",\"lock-cf-compact-interval\":\"10m\",\"lock-cf-compact-bytes-threshold\":\"256MB\",\"notify-capacity\":40960,\"messages-per-tick\":4096,\"max-peer-down-duration\":\"5m\",\"max-leader-missing-duration\":\"2h\",\"abnormal-leader-missing-duration\":\"10m\",\"peer-stale-state-check-interval\":\"5m\",\"leader-transfer-max-log-lag\":10,\"snap-apply-batch-size\":\"10MB\",\"consistency-check-interval\":\"0s\",\"report-region-flow-interval\":\"1m\",\"raft-store-max-leader-lease\":\"9s\",\"right-derive-when-split\":true,\"allow-remove-leader\":false,\"merge-max-log-gap\":10,\"merge-check-tick-interval\":\"10s\",\"use-delete-range\":false,\"cleanup-import-sst-interval\":\"10m\",\"local-read-batch-size\":1024,\"apply-max-batch-size\":1024,\"apply-pool-size\":2,\"store-max-batch-size\":1024,\"store-pool-size\":2,\"future-poll-size\":1},\"coprocessor\":{\"split-region-on-table\":true,\"batch-split-limit\":10,\"region-max-size\":\"144MB\",\"region-split-size\":\"96MB\",\"region-max-keys\":1440000,\"region-split-keys\":960000},\"rocksdb\":{\"wal-recovery-mode\":2,\"wal-dir\":\"\",\"wal-ttl-seconds\":0,\"wal-size-limit\":\"0KB\",\"max-total-wal-size\":\"4GB\",\"max-background-jobs\":6,\"max-manifest-file-size\":\"128MB\",\"create-if-missing\":true,\"max-open-files\":40960,\"enable-statistics\":true,\"stats-dump-period\":\"10m\",\"compaction-readahead-size\":\"0KB\",\"info-log-max-size\":\"1GB\",\"info-log-roll-time\":\"0s\",\"info-log-keep-log-file-num\":10,\"info-log-dir\":\"\",\"rate-bytes-per-sec\":\"0KB\",\"rate-limiter-mode\":2,\"auto-tuned\":false,\"bytes-per-sync\":\"1MB\",\"wal-bytes-per-sync\":\"512KB\",\"max-sub-compactions\":1,\"writable-file-max-buffer-size\":\"1MB\",\"use-direct-io-for-flush-and-compaction\":false,\"enable-pipelined-write\":true,\"defaultcf\":{\"block-size\":\"64KB\",\"block-cache-size\":\"245MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":true,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"lz4\",\"lz4\",\"lz4\",\"zstd\",\"zstd\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"512MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":4,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":3,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":1024,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"writecf\":{\"block-size\":\"64KB\",\"block-cache-size\":\"147MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":false,\"whole-key-filtering\":false,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"lz4\",\"lz4\",\"lz4\",\"zstd\",\"zstd\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"512MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":4,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":3,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":4294967296,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"lockcf\":{\"block-size\":\"16KB\",\"block-cache-size\":\"256MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":false,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"no\",\"no\",\"no\",\"no\",\"no\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"128MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":1,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":0,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":4294967296,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"raftcf\":{\"block-size\":\"16KB\",\"block-cache-size\":\"128MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":true,\"optimize-filters-for-hits\":true,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"no\",\"no\",\"no\",\"no\",\"no\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"128MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":1,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":0,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":4294967296,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}},\"titan\":{\"enabled\":false,\"dirname\":\"\",\"disable-gc\":false,\"max-background-gc\":1}},\"raftdb\":{\"wal-recovery-mode\":2,\"wal-dir\":\"\",\"wal-ttl-seconds\":0,\"wal-size-limit\":\"0KB\",\"max-total-wal-size\":\"4GB\",\"max-background-jobs\":2,\"max-manifest-file-size\":\"20MB\",\"create-if-missing\":true,\"max-open-files\":40960,\"enable-statistics\":true,\"stats-dump-period\":\"10m\",\"compaction-readahead-size\":\"0KB\",\"info-log-max-size\":\"1GB\",\"info-log-roll-time\":\"0s\",\"info-log-keep-log-file-num\":10,\"info-log-dir\":\"\",\"max-sub-compactions\":1,\"writable-file-max-buffer-size\":\"1MB\",\"use-direct-io-for-flush-and-compaction\":false,\"enable-pipelined-write\":true,\"allow-concurrent-memtable-write\":false,\"bytes-per-sync\":\"1MB\",\"wal-bytes-per-sync\":\"512KB\",\"defaultcf\":{\"block-size\":\"64KB\",\"block-cache-size\":\"256MB\",\"disable-block-cache\":false,\"cache-index-and-filter-blocks\":true,\"pin-l0-filter-and-index-blocks\":true,\"use-bloom-filter\":false,\"optimize-filters-for-hits\":true,\"whole-key-filtering\":true,\"bloom-filter-bits-per-key\":10,\"block-based-bloom-filter\":false,\"read-amp-bytes-per-bit\":0,\"compression-per-level\":[\"no\",\"no\",\"lz4\",\"lz4\",\"lz4\",\"zstd\",\"zstd\"],\"write-buffer-size\":\"128MB\",\"max-write-buffer-number\":5,\"min-write-buffer-number-to-merge\":1,\"max-bytes-for-level-base\":\"512MB\",\"target-file-size-base\":\"8MB\",\"level0-file-num-compaction-trigger\":4,\"level0-slowdown-writes-trigger\":20,\"level0-stop-writes-trigger\":36,\"max-compaction-bytes\":\"2GB\",\"compaction-pri\":0,\"dynamic-level-bytes\":true,\"num-levels\":7,\"max-bytes-for-level-multiplier\":10,\"compaction-style\":0,\"disable-auto-compactions\":false,\"soft-pending-compaction-bytes-limit\":\"64GB\",\"hard-pending-compaction-bytes-limit\":\"256GB\",\"titan\":{\"min-blob-size\":1024,\"blob-file-compression\":\"lz4\",\"blob-cache-size\":\"0KB\",\"min-gc-batch-size\":\"16MB\",\"max-gc-batch-size\":\"64MB\",\"discardable-ratio\":0.5,\"sample-ratio\":0.1,\"merge-small-file-threshold\":\"8MB\"}}},\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cipher-file\":\"\"},\"import\":{\"import-dir\":\"/tmp/tikv/import\",\"num-threads\":8,\"num-import-jobs\":8,\"num-import-sst-jobs\":2,\"max-prepare-duration\":\"5m\",\"region-split-size\":\"512MB\",\"stream-channel-window\":128,\"max-open-engines\":8}}"]
[2019/03/31 16:19:26.038 +00:00] [ERROR] [tikv-server.rs:75] ["the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"]
```

I am going to close this issue.
